spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: crow-erp-config # 命名空间
        group: crow-erp-config     # 组名
        file-extension: yaml       # 扩展名
        encode: UTF-8

  config:
    import: nacos:crow-erp-gateway-config,nacos:crow-erp-public # 多个已 , 隔开