spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: crow-erp-config
        group: crow-erp-config
        file-extension: yaml
  config:
    import: nacos:crow-erp-system-config